/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedZonesRouteImport } from './routes/_authenticated/zones'
import { Route as AuthenticatedRecapRouteImport } from './routes/_authenticated/recap'
import { Route as AuthenticatedModerateRouteImport } from './routes/_authenticated/moderate'
import { Route as ApiPublicRegisterPushTokenRouteImport } from './routes/api/public/register-push-token'
import { Route as ApiPublicIngestLocationRouteImport } from './routes/api/public/ingest-location'
import { Route as ApiPublicCronPushRecapsRouteImport } from './routes/api/public/cron/push-recaps'
import { Route as ApiPublicCronNotifyApprovalsRouteImport } from './routes/api/public/cron/notify-approvals'
import { Route as ApiPublicCronGenerateRecapRouteImport } from './routes/api/public/cron/generate-recap'
import { Route as ApiPublicCronGeneratePulseRouteImport } from './routes/api/public/cron/generate-pulse'
import { Route as ApiPublicAuthSignupRouteImport } from './routes/api/public/auth/signup'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZonesRoute = AuthenticatedZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecapRoute = AuthenticatedRecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModerateRoute = AuthenticatedModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicRegisterPushTokenRoute =
  ApiPublicRegisterPushTokenRouteImport.update({
    id: '/api/public/register-push-token',
    path: '/api/public/register-push-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIngestLocationRoute = ApiPublicIngestLocationRouteImport.update({
  id: '/api/public/ingest-location',
  path: '/api/public/ingest-location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPushRecapsRoute = ApiPublicCronPushRecapsRouteImport.update({
  id: '/api/public/cron/push-recaps',
  path: '/api/public/cron/push-recaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotifyApprovalsRoute =
  ApiPublicCronNotifyApprovalsRouteImport.update({
    id: '/api/public/cron/notify-approvals',
    path: '/api/public/cron/notify-approvals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGenerateRecapRoute =
  ApiPublicCronGenerateRecapRouteImport.update({
    id: '/api/public/cron/generate-recap',
    path: '/api/public/cron/generate-recap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGeneratePulseRoute =
  ApiPublicCronGeneratePulseRouteImport.update({
    id: '/api/public/cron/generate-pulse',
    path: '/api/public/cron/generate-pulse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSignupRoute = ApiPublicAuthSignupRouteImport.update({
  id: '/api/public/auth/signup',
  path: '/api/public/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/api/public/ingest-location': typeof ApiPublicIngestLocationRoute
  '/api/public/register-push-token': typeof ApiPublicRegisterPushTokenRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/cron/generate-pulse': typeof ApiPublicCronGeneratePulseRoute
  '/api/public/cron/generate-recap': typeof ApiPublicCronGenerateRecapRoute
  '/api/public/cron/notify-approvals': typeof ApiPublicCronNotifyApprovalsRoute
  '/api/public/cron/push-recaps': typeof ApiPublicCronPushRecapsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/moderate': typeof AuthenticatedModerateRoute
  '/recap': typeof AuthenticatedRecapRoute
  '/zones': typeof AuthenticatedZonesRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/ingest-location': typeof ApiPublicIngestLocationRoute
  '/api/public/register-push-token': typeof ApiPublicRegisterPushTokenRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/cron/generate-pulse': typeof ApiPublicCronGeneratePulseRoute
  '/api/public/cron/generate-recap': typeof ApiPublicCronGenerateRecapRoute
  '/api/public/cron/notify-approvals': typeof ApiPublicCronNotifyApprovalsRoute
  '/api/public/cron/push-recaps': typeof ApiPublicCronPushRecapsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/moderate': typeof AuthenticatedModerateRoute
  '/_authenticated/recap': typeof AuthenticatedRecapRoute
  '/_authenticated/zones': typeof AuthenticatedZonesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/ingest-location': typeof ApiPublicIngestLocationRoute
  '/api/public/register-push-token': typeof ApiPublicRegisterPushTokenRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/cron/generate-pulse': typeof ApiPublicCronGeneratePulseRoute
  '/api/public/cron/generate-recap': typeof ApiPublicCronGenerateRecapRoute
  '/api/public/cron/notify-approvals': typeof ApiPublicCronNotifyApprovalsRoute
  '/api/public/cron/push-recaps': typeof ApiPublicCronPushRecapsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/moderate'
    | '/recap'
    | '/zones'
    | '/api/public/ingest-location'
    | '/api/public/register-push-token'
    | '/api/public/auth/signup'
    | '/api/public/cron/generate-pulse'
    | '/api/public/cron/generate-recap'
    | '/api/public/cron/notify-approvals'
    | '/api/public/cron/push-recaps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/moderate'
    | '/recap'
    | '/zones'
    | '/'
    | '/api/public/ingest-location'
    | '/api/public/register-push-token'
    | '/api/public/auth/signup'
    | '/api/public/cron/generate-pulse'
    | '/api/public/cron/generate-recap'
    | '/api/public/cron/notify-approvals'
    | '/api/public/cron/push-recaps'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/moderate'
    | '/_authenticated/recap'
    | '/_authenticated/zones'
    | '/_authenticated/'
    | '/api/public/ingest-location'
    | '/api/public/register-push-token'
    | '/api/public/auth/signup'
    | '/api/public/cron/generate-pulse'
    | '/api/public/cron/generate-recap'
    | '/api/public/cron/notify-approvals'
    | '/api/public/cron/push-recaps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicIngestLocationRoute: typeof ApiPublicIngestLocationRoute
  ApiPublicRegisterPushTokenRoute: typeof ApiPublicRegisterPushTokenRoute
  ApiPublicAuthSignupRoute: typeof ApiPublicAuthSignupRoute
  ApiPublicCronGeneratePulseRoute: typeof ApiPublicCronGeneratePulseRoute
  ApiPublicCronGenerateRecapRoute: typeof ApiPublicCronGenerateRecapRoute
  ApiPublicCronNotifyApprovalsRoute: typeof ApiPublicCronNotifyApprovalsRoute
  ApiPublicCronPushRecapsRoute: typeof ApiPublicCronPushRecapsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones': {
      id: '/_authenticated/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AuthenticatedZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recap': {
      id: '/_authenticated/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof AuthenticatedRecapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderate': {
      id: '/_authenticated/moderate'
      path: '/moderate'
      fullPath: '/moderate'
      preLoaderRoute: typeof AuthenticatedModerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/register-push-token': {
      id: '/api/public/register-push-token'
      path: '/api/public/register-push-token'
      fullPath: '/api/public/register-push-token'
      preLoaderRoute: typeof ApiPublicRegisterPushTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-location': {
      id: '/api/public/ingest-location'
      path: '/api/public/ingest-location'
      fullPath: '/api/public/ingest-location'
      preLoaderRoute: typeof ApiPublicIngestLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/push-recaps': {
      id: '/api/public/cron/push-recaps'
      path: '/api/public/cron/push-recaps'
      fullPath: '/api/public/cron/push-recaps'
      preLoaderRoute: typeof ApiPublicCronPushRecapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify-approvals': {
      id: '/api/public/cron/notify-approvals'
      path: '/api/public/cron/notify-approvals'
      fullPath: '/api/public/cron/notify-approvals'
      preLoaderRoute: typeof ApiPublicCronNotifyApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/generate-recap': {
      id: '/api/public/cron/generate-recap'
      path: '/api/public/cron/generate-recap'
      fullPath: '/api/public/cron/generate-recap'
      preLoaderRoute: typeof ApiPublicCronGenerateRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/generate-pulse': {
      id: '/api/public/cron/generate-pulse'
      path: '/api/public/cron/generate-pulse'
      fullPath: '/api/public/cron/generate-pulse'
      preLoaderRoute: typeof ApiPublicCronGeneratePulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup': {
      id: '/api/public/auth/signup'
      path: '/api/public/auth/signup'
      fullPath: '/api/public/auth/signup'
      preLoaderRoute: typeof ApiPublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedModerateRoute: typeof AuthenticatedModerateRoute
  AuthenticatedRecapRoute: typeof AuthenticatedRecapRoute
  AuthenticatedZonesRoute: typeof AuthenticatedZonesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedModerateRoute: AuthenticatedModerateRoute,
  AuthenticatedRecapRoute: AuthenticatedRecapRoute,
  AuthenticatedZonesRoute: AuthenticatedZonesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicIngestLocationRoute: ApiPublicIngestLocationRoute,
  ApiPublicRegisterPushTokenRoute: ApiPublicRegisterPushTokenRoute,
  ApiPublicAuthSignupRoute: ApiPublicAuthSignupRoute,
  ApiPublicCronGeneratePulseRoute: ApiPublicCronGeneratePulseRoute,
  ApiPublicCronGenerateRecapRoute: ApiPublicCronGenerateRecapRoute,
  ApiPublicCronNotifyApprovalsRoute: ApiPublicCronNotifyApprovalsRoute,
  ApiPublicCronPushRecapsRoute: ApiPublicCronPushRecapsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
